# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "36a7979942bccad6d97720c96b04d0f3"
name = "return-refund-monitor"
handle = "return-refund-monitor"
application_url = "https://argued-detail-boxing-promotes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "return-refund-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,read_customers,read_orders,unauthenticated_read_checkouts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://argued-detail-boxing-promotes.trycloudflare.com/auth/callback",
  "https://argued-detail-boxing-promotes.trycloudflare.com/auth/shopify/callback",
  "https://argued-detail-boxing-promotes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
